<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AssrBuilding;

class AssrBuildingSeeder extends Seeder
{
    public function run(): void
    {
        $buildings = [
            [
                'TDNo' => 'EB-010-04722',
                'Area' => 8,
                'Roof' => 'R.C',
                '1stFlooring' => null,
                '2ndFlooring' => null,
                '3rdFlooring' => null,
                '4thFlooring' => null,
                'Description' => 'SERVICE AREA 214',
                'Unit_Value' => 0,
                'Market_Value' => 59200,
                'Remarks' => 'R.C',
                'TypeOfStructure' => 'Residential',
                'AU' => 0,
                'AL' => 0,
                'AV' => 0,
                'Story' => '1st Storey',
                'Exempt' => 0,
                'Additional' => 0,
                'AdjLvl' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'TDNo' => 'EB-012-00002',
                'Area' => 229.5,
                'Roof' => 'CHB STRONG',
                '1stFlooring' => null,
                '2ndFlooring' => null,
                '3rdFlooring' => null,
                '4thFlooring' => null,
                'Description' => 'FACTORY BLDG',
                'Unit_Value' => 450.02,
                'Market_Value' => 103280,
                'Remarks' => null,
                'TypeOfStructure' => 'Residential',
                'AU' => 50,
                'AL' => 51640,
                'AV' => 0,
                'Story' => null,
                'Exempt' => 1,
                'Additional' => 0,
                'AdjLvl' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'TDNo' => 'EB-010-06065',
                'Area' => 65,
                'Roof' => 'R.C.',
                '1stFlooring' => null,
                '2ndFlooring' => null,
                '3rdFlooring' => null,
                '4thFlooring' => null,
                'Description' => 'CONDO UNIT 526',
                'Unit_Value' => 0,
                'Market_Value' => 1040000,
                'Remarks' => 'R.C.',
                'TypeOfStructure' => 'Residential',
                'AU' => 60,
                'AL' => 624000,
                'AV' => 0,
                'Story' => '1st Storey',
                'Exempt' => 0,
                'Additional' => 0,
                'AdjLvl' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'TDNo' => 'EB-010-06065',
                'Area' => 10,
                'Roof' => null,
                '1stFlooring' => null,
                '2ndFlooring' => null,
                '3rdFlooring' => null,
                '4thFlooring' => null,
                'Description' => 'BALCONY',
                'Unit_Value' => 0,
                'Market_Value' => 72000,
                'Remarks' => 'additional',
                'TypeOfStructure' => 'Residential',
                'AU' => 60,
                'AL' => 43200,
                'AV' => 0,
                'Story' => null,
                'Exempt' => 0,
                'Additional' => 1,
                'AdjLvl' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'TDNo' => 'EB-012-00002',
                'Area' => 24.5,
                'Roof' => 'CHB',
                '1stFlooring' => null,
                '2ndFlooring' => null,
                '3rdFlooring' => null,
                '4thFlooring' => null,
                'Description' => 'CANTEEN',
                'Unit_Value' => 199.18,
                'Market_Value' => 4880,
                'Remarks' => null,
                'TypeOfStructure' => 'Residential',
                'AU' => 50,
                'AL' => 2440,
                'AV' => 0,
                'Story' => null,
                'Exempt' => 1,
                'Additional' => 0,
                'AdjLvl' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($buildings as $building) {
            AssrBuilding::create($building);
        }
    }
}