<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AssrInformation;

class AssrInformationSeeder extends Seeder
{
    public function run(): void
    {
        $informations = [
            [
                'TDNo' => 'EB-016-00055',
                'PIDNo' => null,
                'Owner' => 'ZENAIDA CARPIO',
                'Address' => 'BLK. 4, LOT.42, PH I, DREAMVILLE HOMES, LIGID TIPAS TAGUIG CITY',
                'TelNo' => null,
                'TIN' => null,
                'Administrator' => null,
                'Address2' => 'BLK. 4, LOT.42, PH I, DREAMVILLE HOMES',
                'TelNo2' => null,
                'TIN2' => null,
                'LOP_HouseNo' => null,
                'LOP_Street' => null,
                'LOP_Barangay' => 'LIGID-TIPAS',
                'LOP_Municipality' => null,
                'KOP' => 'BUILDING',
                'Taxable' => 'Taxable',
                'EARQtr' => '1st',
                'EARYear' => 2007,
                'DRDate' => '01/03/2007',
                'AppraisedBy' => '[gonzalese] Emmanuel Joshua Gonzales',
                'ABDate' => null,
                'RA' => 'NEW DECLARATION / DISCOVERY',
                'RADate' => null,
                'AprovedBy' => null,
                'DateAproved' => null,
                'Annotation' => 'ON THE LAND OF ANTONIA DINGUINBAYAN T.D FL-016-00713',
                'Memoranda' => null,
                'Requirements' => null,
                'Status' => 'VALIDATED',
                'LastProcessed' => null,
                'Transaction' => null,
                'Remarks' => null,
                'Barangay' => 'LIGID-TIPAS',
                'TitleNumber' => null,
                'LotNumber' => null,
                'BlockNumber' => null,
                'SurveyNum' => null,
                'North' => null,
                'East' => null,
                'West' => null,
                'South' => null,
                'AssessmentLevel' => '10%',
                'Kind' => 'HOUSE',
                'ActualUse' => 'RESIDENTIAL',
                'TCTDated' => null,
                'landRef' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'TDNo' => 'EB-001-00995',
                'PIDNo' => null,
                'Owner' => 'RENAISSANCE PRINTING SERVICES INC.',
                'Address' => '1ST AVE. EXT, SANTA MARIA REAL ESTATE SUBD., BAGUMBAYAN, TAGUIG CITY',
                'TelNo' => null,
                'TIN' => null,
                'Administrator' => null,
                'Address2' => '1ST AVE. EXT, SANTA MARIA REAL ESTATE SUBD.',
                'TelNo2' => null,
                'TIN2' => null,
                'LOP_HouseNo' => null,
                'LOP_Street' => null,
                'LOP_Barangay' => 'BAGUMBAYAN',
                'LOP_Municipality' => null,
                'KOP' => 'BUILDING',
                'Taxable' => 'Taxable',
                'EARQtr' => '1st',
                'EARYear' => 2014,
                'DRDate' => '05/09/2013',
                'AppraisedBy' => '[gayaness] Shyrine Gay M. Gayanes',
                'ABDate' => null,
                'RA' => 'REASSESSMENT',
                'RADate' => null,
                'AprovedBy' => null,
                'DateAproved' => null,
                'Annotation' => 'ON THE LAND OF GL-001-04950',
                'Memoranda' => null,
                'Requirements' => null,
                'Status' => 'VALIDATED',
                'LastProcessed' => null,
                'Transaction' => null,
                'Remarks' => null,
                'Barangay' => 'BAGUMBAYAN',
                'TitleNumber' => null,
                'LotNumber' => null,
                'BlockNumber' => null,
                'SurveyNum' => null,
                'North' => null,
                'East' => null,
                'West' => null,
                'South' => null,
                'AssessmentLevel' => '75%',
                'Kind' => 'WAREHOUSE',
                'ActualUse' => 'COMMERCIAL',
                'TCTDated' => null,
                'landRef' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'TDNo' => 'EB-001-00996',
                'PIDNo' => null,
                'Owner' => 'AMARLEX P. BIJASA, MARIANNE P. BIJASA, ANDREW P. BIJASA MARK ANDREW T. BIJASA 1/4 SHARE',
                'Address' => 'LOT 17 BLK 1 NO. 116 HOLY FAMILY AVE., HFV, BAGUMBAYAN, TAGUIG CITY',
                'TelNo' => null,
                'TIN' => null,
                'Administrator' => null,
                'Address2' => 'LOT 17 BLK 1 NO. 116 HOLY FAMILY AVE., HFV',
                'TelNo2' => null,
                'TIN2' => null,
                'LOP_HouseNo' => null,
                'LOP_Street' => null,
                'LOP_Barangay' => 'BAGUMBAYAN',
                'LOP_Municipality' => null,
                'KOP' => 'BUILDING',
                'Taxable' => 'Taxable',
                'EARQtr' => '1st',
                'EARYear' => 2014,
                'DRDate' => '05/13/2013',
                'AppraisedBy' => '[gayaness] Shyrine Gay M. Gayanes',
                'ABDate' => null,
                'RA' => 'TRANSFER OF OWNERSHIP & REASSESSMENT',
                'RADate' => null,
                'AprovedBy' => null,
                'DateAproved' => null,
                'Annotation' => 'ON THE LAND OF SAME NAME TD# GL-001-04956',
                'Memoranda' => null,
                'Requirements' => null,
                'Status' => 'VALIDATED',
                'LastProcessed' => null,
                'Transaction' => null,
                'Remarks' => null,
                'Barangay' => 'BAGUMBAYAN',
                'TitleNumber' => null,
                'LotNumber' => null,
                'BlockNumber' => null,
                'SurveyNum' => null,
                'North' => null,
                'East' => null,
                'West' => null,
                'South' => null,
                'AssessmentLevel' => '25%',
                'Kind' => 'HOUSE',
                'ActualUse' => 'RESIDENTIAL',
                'TCTDated' => null,
                'landRef' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'TDNo' => 'EB-001-01006',
                'PIDNo' => null,
                'Owner' => 'NOEL N. PAGCALIWANGAN',
                'Address' => '#79 ROAD 6, JOSEPH SITT ST., BAGUMBAYAN, TAGUIG CITY',
                'TelNo' => null,
                'TIN' => null,
                'Administrator' => null,
                'Address2' => '#79 ROAD 6, JOSEPH SITT ST.',
                'TelNo2' => null,
                'TIN2' => null,
                'LOP_HouseNo' => null,
                'LOP_Street' => null,
                'LOP_Barangay' => 'BAGUMBAYAN',
                'LOP_Municipality' => null,
                'KOP' => 'BUILDING',
                'Taxable' => 'Taxable',
                'EARQtr' => '1st',
                'EARYear' => 2014,
                'DRDate' => '09/12/2013',
                'AppraisedBy' => '[GAYANESS] Shyrine Gay M. Gayanes',
                'ABDate' => null,
                'RA' => 'TRANSFER OF OWNERSHIP/ REASSESSMENT',
                'RADate' => null,
                'AprovedBy' => null,
                'DateAproved' => null,
                'Annotation' => 'ON THE LAND OF JOSEPH SITT HOMEOWNERS ASS\'N.',
                'Memoranda' => null,
                'Requirements' => null,
                'Status' => 'VALIDATED',
                'LastProcessed' => null,
                'Transaction' => null,
                'Remarks' => null,
                'Barangay' => 'BAGUMBAYAN',
                'TitleNumber' => null,
                'LotNumber' => null,
                'BlockNumber' => null,
                'SurveyNum' => null,
                'North' => null,
                'East' => null,
                'West' => null,
                'South' => null,
                'AssessmentLevel' => '35%',
                'Kind' => 'HOUSE',
                'ActualUse' => 'RESIDENTIAL',
                'TCTDated' => null,
                'landRef' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'TDNo' => 'EB-001-01010',
                'PIDNo' => null,
                'Owner' => 'MARIO C. POON',
                'Address' => '140-M MLQ. ST. PH-2, NEW LOWER BICUTAN, TAGUIG CITY',
                'TelNo' => null,
                'TIN' => null,
                'Administrator' => null,
                'Address2' => 'LOT 3, BLK 12, #246 STO. NIÑO ST., HOLY FAMILY VILLAGE',
                'TelNo2' => null,
                'TIN2' => null,
                'LOP_HouseNo' => null,
                'LOP_Street' => null,
                'LOP_Barangay' => 'BAGUMBAYAN',
                'LOP_Municipality' => null,
                'KOP' => 'BUILDING',
                'Taxable' => 'Taxable',
                'EARQtr' => '1st',
                'EARYear' => 2014,
                'DRDate' => '09/13/2013',
                'AppraisedBy' => '[GAYANESS] Shyrine Gay M. Gayanes',
                'ABDate' => null,
                'RA' => 'TRANSFER OF OWNERSHIP W/ REASSESSMENT',
                'RADate' => null,
                'AprovedBy' => null,
                'DateAproved' => null,
                'Annotation' => 'ON THE LAND OF GL-001-04994',
                'Memoranda' => null,
                'Requirements' => null,
                'Status' => 'VALIDATED',
                'LastProcessed' => null,
                'Transaction' => null,
                'Remarks' => null,
                'Barangay' => 'BAGUMBAYAN',
                'TitleNumber' => null,
                'LotNumber' => null,
                'BlockNumber' => null,
                'SurveyNum' => null,
                'North' => null,
                'East' => null,
                'West' => null,
                'South' => null,
                'AssessmentLevel' => '30%',
                'Kind' => 'HOUSE',
                'ActualUse' => 'RESIDENTIAL',
                'TCTDated' => null,
                'landRef' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($informations as $information) {
            AssrInformation::create($information);
        }
    }
}
